### ISSUE TITLE
Enable MQTT SSL connexions

### ISSUE THREAD

**Issue by goldendatahub** [yukulehe/gazpar2mqtt#14]
Enable MQTT SSL connexions

**Comment by goldendatahub** [comment]
@Minims 
Je vais ajouter un paramètre boolean pour activer le SSL.
Y'a t-il besoin faire quelque chose au niveau du certificat ? J'ai vu que tu l'as mis à CERT_NONE.

J'ai modifié le constructeur dans le fichier mqtt.py :

```
# Sub constructor
def create_client(clientId,username,password,ssl):
    
    # Create instance
    client = mqtt.Client(clientId)
    
    # Set authentification
    if username != "" and password != "":
        client.username_pw_set(username, password)
    
    # Set SSL if required
    ssl_boolean = False
    ssl_boolean = ssl.lower() in ("t","true","1","Yes","Y","Yup","Oui","Si","Da")
    if ssl_boolean:
        client.tls_set(cert_reqs=ssl.CERT_NONE)
        client.tls_insecure_set(True)
    
    return client
```

**Comment by goldendatahub** [comment]
Fix en v0.4.3, par contre j'ai pas pu tester

**Comment by Minims** [comment]
Ca suffit pour un usage basic. 
Sinon il faut gérer le certificat coté client, c'est plus compliqué pour du clé en main.
La deja c'est chiffré, c'est deja bien.
Je teste après

**Comment by Minims** [comment]
J'ai ajouté un bout de log mais ca deconne : 

```
2021-11-19 17:43:17,780 Connect to Mqtt broker...
2021-11-19 17:43:17,780 'str' object has no attribute 'CERT_NONE'
2021-11-19 17:43:17,780 Unable to connect to Mqtt broker. Please check that broker is running, or check broker configuration.
```

**Comment by Minims** [comment]
c'est ta variable ssl le soucis. soit tu la changes, soit tu renommes l'import

```
def create_client(clientId,username,password,ssl):
```

sinon

```
import ssl as ssl_lib
...
        client.tls_set(cert_reqs=ssl_lib.CERT_NONE)
```

**Comment by goldendatahub** [comment]
merci, je regarde

**Comment by goldendatahub** [comment]
j'ai renommé la variable en v0.4.4

**Comment by goldendatahub** [comment]
si tu veux tester avant que je merge

**Comment by Minims** [comment]
Ca m'a l'air ok pour le SSL. ca se connecte bien.

**Comment by goldendatahub** [comment]
Cool. Je publie du coup.
