### ISSUE TITLE
Keep secret 

### ISSUE THREAD

**Issue by aladin2000** [yukulehe/gazpar2mqtt#24]
bonjour à toi 
je voulais savoir si on pouvait avoir les infos de connexion de cet addon gardées secrétes dans HA
comme par exemple  

GRDF_USERNAME: !secret grdf.username 
[11:01:12] FATAL: gazpar.username does not follow the structure KEY=text, it will be ignored and removed from the config

**Comment by goldendatahub** [comment]
@alexbelgium Salut Alex, penses-tu pouvoir faire quelque chose pour aladin ?

**Comment by alexbelgium** [comment]
Bonjour, quel est l'inconvénient de l'avoir dans le log ? Car personne n'y a accès à part toi ? C'est juste pour comprendre le soucis car techniquement ce sera faisable

**Comment by goldendatahub** [comment]
Je n'ai peut être pas compris ta réponse Alex et je ne connais pas bien non plus la partie add-on de HA. Mais je suppose que c'est pour avoir un docker_compose qui ne stocke pas le password ?
Du coup ça se passe de quel côté pour gérer les paramètres !secret ? Add-on ou appli ?

**Comment by aladin2000** [comment]
Bjr
Pour être conforme aux logiques présentes depuis le début dans ha
Tous mes mdp sont codes dans un seul fichier secrets.yaml

Plus difficile à lire pour autrui et eviter d'avoir des mdp partout
Si c'est pas difficile le repérage du tag secret qui donne l'ouverture du fichier centralisé. ...

1 déc. 2021 12:02:01 Alexandre ***@***.***>:

**Comment by alexbelgium** [comment]
Je vais pusher une version "0.5_dev_dontupdate", pourrais tu tester? C'était au final beaucoup plus compliqué que ce que je pensais à implémenter mais cela pourrait fonctionner. Ma seule crainte est que cela interfère avec les autres variables. Merci d'avance pour le test

EDIT : le test ne fonctionne pas je dois investiguer plus en profondeur

**Comment by aladin2000** [comment]
> 
je reste à ta disposition...  Cela concernerait également le adon enedis2mqtt ... ou le token, le PDL sont aussi en clair....

**Comment by alexbelgium** [comment]
J'ai pushé une version test si tu as l'occasion de tester ce serait top

**Comment by aladin2000** [comment]
Je le fais DQP

1 déc. 2021 23:21:19 Alexandre ***@***.***>:

**Comment by aladin2000** [comment]
Merci bcp
Cela fonctionne avec. Ta dernière version


1 déc. 2021 23:55:59 Aladin ***@***.***>:

**Comment by alexbelgium** [comment]
Sorry, ça faisait crasher d'autres (https://github.com/alexbelgium/hassio-addons/issues/99) j'ai du enlever l'option secrets. Je vais refaire des tests...

**Comment by aladin2000** [comment]
Secret C'est ok si je mets pas à jour .... ?

2 déc. 2021 11:33:13 Alexandre ***@***.***>:

**Comment by alexbelgium** [comment]
Bonne idée. Je te fais signe quand une nouvelle version avec secret est en ligne

**Comment by alexbelgium** [comment]
Bonjour, la version 0.5.1-4 devrait maintenant fonctionner pour tout le monde et inclue le mode secret

**Comment by goldendatahub** [comment]
https://github.com/alexbelgium/hassio-addons/issues/99
