### ISSUE TITLE
Credential from config.yaml issue

### ISSUE THREAD

**Issue by echauvet** [yukulehe/gazpar2mqtt#27]
Sans rien changer à la configuration je vois dans les traces que GRDF_USERNAME est bien lu mais je tombe sur ce message :
 
 ​        ​logging​.​error​(​"Parameter GRDF username is mandatory."​)

**Comment by goldendatahub** [comment]
Je n'ai pas le souci. T'es sur l'add-on ?

**Comment by goldendatahub** [comment]
Une issue a été ouverte sur l'add-on : https://github.com/alexbelgium/hassio-addons/issues/99

**Comment by echauvet** [comment]
> Une issue a été ouverte sur l'add-on : https://github.com/alexbelgium/hassio-addons/issues/99

Ok. Effectivement.
