### ISSUE TITLE
Syntax error on mqtt connexion with username/password

### ISSUE THREAD

**Issue by echauvet** [yukulehe/gazpar2mqtt#28]
​        ​# Set authentification 
 ​        ​if​ ​username​ ​!=​ ​""​ ​and​ ​password​ ​!=​ ​""​: 
 ​            ​client​.​username_pw_set​(​username​, ​password​)

Did you mean self.client line 21 of mqtt.py?

**Comment by goldendatahub** [comment]
Bien vu ! Corrigé en 0.5.2.

**Comment by goldendatahub** [comment]
corrigé direct dans le main (0.5.1) car regression

**Comment by echauvet** [comment]
Pour le moment l'add on n'a pas été mis à jour.
