### ISSUE TITLE
Erreur connexion GRDF corrigée

### ISSUE THREAD

**Issue by Ericd80** [yukulehe/gazpar2mqtt#35]
Bonjour
Merci pour votre réponse rapide
Pour info
Après  nouveaux tests comme vous le recommandiez et "avoir mieux lu le log" en faite mon problème de connexion bloquait sur mon mot de passe
Celui ci comportait un &  et un % 
Depuis changement du mdp sur le site de GRDF celui-ci passe dans votre appli 
Merci et Bravo pour la modif
Je vais pouvoir poursuivre sur l'intégration mqtt pour Domoticz que je n'ai pas encore vraiment testé du coup

**Comment by goldendatahub** [comment]
Cool. Content de voir un utilisateur de Domoticz qui utilise l'app.
