### ISSUE TITLE
0.6-dev : daily_gas et gas incohérents

### ISSUE THREAD

**Issue by DamGranger** [yukulehe/gazpar2mqtt#36]
Dans la 0.6-dev, le daily_gas et gas reprennent tel quel le volumeConsomme de GRDF, cependant toutes les autres mesures de volumes semblent utiliser une différence entre indexFin et indexDebut. Dans mon exemple cela génère une petite différence, notamment avec Day-3 gas alors qu'il s'agit réellement de la même mesure, ce qui est dommage.

![image](https://user-images.githubusercontent.com/93887648/145436796-cbe18bf1-d853-4c50-8a32-02a709e16310.png)

Par souci de cohérence, je pense qu'il faudrait que tous les volumes soient calculés de la même façon, même si en cas de "trous" cela risque de poser problème (exemple ci-dessous), à moins qu'il soit possible de dynamiquement remplacer le indexDebut par le dernier indexFin connu :

```
            {
                "coeffConversion": 10.73,
                "dateDebutReleve": "2021-02-08T06:00:00+01:00",
                "dateFinReleve": "2021-02-09T06:00:00+01:00",
                "energieConsomme": 164,
                "frequenceReleve": null,
                "indexDebut": 10769,
                "indexFin": 10784,
                "journeeGaziere": "2021-02-08",
                "natureReleve": "Informative Journalier",
                "pcs": null,
                "pta": null,
                "qualificationReleve": "Mesur\u00e9",
                "status": null,
                "temperature": null,
                "volumeBrutConsomme": 15,
                "volumeConverti": null
            },
            {
                "coeffConversion": null,
                "dateDebutReleve": "2021-02-09T06:00:00+01:00",
                "dateFinReleve": "2021-02-10T06:00:00+01:00",
                "energieConsomme": null,
                "frequenceReleve": null,
                "indexDebut": null,
                "indexFin": null,
                "journeeGaziere": "2021-02-09",
                "natureReleve": null,
                "pcs": null,
                "pta": null,
                "qualificationReleve": "Absence de Donn\u00e9es",
                "status": null,
                "temperature": null,
                "volumeBrutConsomme": null,
                "volumeConverti": null
            },
            {
                "coeffConversion": 10.73,
                "dateDebutReleve": "2021-02-10T06:00:00+01:00",
                "dateFinReleve": "2021-02-11T06:00:00+01:00",
                "energieConsomme": 177,
                "frequenceReleve": null,
                "indexDebut": null,
                "indexFin": 10815,
                "journeeGaziere": "2021-02-10",
                "natureReleve": "Informative Journalier",
                "pcs": null,
                "pta": null,
                "qualificationReleve": "Mesur\u00e9",
                "status": null,
                "temperature": null,
                "volumeBrutConsomme": 17,
                "volumeConverti": null
            },
```

**Comment by goldendatahub** [comment]
Je suis d'accord pour maintenir une certaine cohérence. Je vais aligner le daily gas (qui est mal nommé car il devrait s'appeler last valid gas) sur les autres indicateurs : à savoir calculer le delta entre le indexFin et indexDebut (si renseigné).
Dans le cas que tu présentes, l'index début est null car le relevé de la veille est manquant. Pour le coup c'est cohérent. Si je remplace par le dernier index fin, je vais mettre une conso trop importante pour ce jour. Le choix est cornelien : soit je présente une info erronnée, soit je présente rien....

Qu'en penses-tu ?

**Comment by DamGranger** [comment]
Honnêtement je n'en pense pas grand chose. Les deux options ont des avantages et inconvénients. D'un côté on a quelque chose de plus homogène mais la gestion des mesures manquantes peut être problématique, de l'autre on a une erreur d'arrondi potentielle avec un écart de 1m3 maximum. 
Le souci c'est que des consommations qui sont pour un appartement ou une petite maison de 9-10m3 par jour, 1m3 c'est quand même une marge d'erreur par anodine.

Du coup faut juste faire un choix et je pense que tu es le mieux placé pour le faire (sachant que dans les deux cas tu auras probablement des questions auxquelles il faudra répondre, donc autant que tu fasses le choix, c'est plus facile à assumer après coup)

**Comment by goldendatahub** [comment]
J'ai appliqué la cohérence dans les calculs : je prends le delta des index, si différent du volume communiqué par GRDF alors je le remplace par le delta et je recalcule l'energie.
En ce qui concerne les relevés sans startIndex, je les considère comme erronés. On verra si ça pose souci sur le long terme.
