### ISSUE TITLE
0.6-dev : previous week of last year

### ISSUE THREAD

**Issue by DamGranger** [yukulehe/gazpar2mqtt#38]
La valeur previous week of last year me semble mal calculée. A moins de sélectionner une plage de 8 jours, je ne retrouve jamais la valeur retournée, en outre j'ai l'impression que c'est plutôt current week of last year.

**Comment by goldendatahub** [comment]
Bien vu, erreur de copier/coller, c'est bien current week of last year.

**Comment by goldendatahub** [comment]
Correction poussée dans docker
