### ISSUE TITLE
password en clair

### ISSUE THREAD

**Issue by aladin2000** [yukulehe/gazpar2mqtt#45]
Bonjour 
Est il normal de voir le mot de passe dans le log de l'addon alors que l'option secret est utilisée
Peux tu le masquer stp ?

**Comment by goldendatahub** [comment]
Salut,
Sauf erreur de ma part, je ne loggue pas les password au niveau de l'app.
Peut-être que c'est spécifique à l'add-on.
Peux-tu faire une issue dans le repo d' @alexbelgium : https://github.com/alexbelgium/hassio-addons ?

**Comment by alexbelgium** [comment]
Bonjour, le log est entièrement privé. Quelqu'un qui aurait accès au log aurait aussi accès au fichier secrets.yaml qui est en clair et donc au mdp... L'objectif de le voir en clair est que le user puisse voir si ses variables sont correctement exportées ou si quelque chose ne fonctionne pas

**Comment by aladin2000** [comment]
Oui je comprends
Mais pourquoi ne pas les sortir qu'en cas de mode débug ?

19 déc. 2021 12:16:04 Alexandre ***@***.***>:

**Comment by alexbelgium** [comment]
J'ai poussé une nouvelle version avec une option "verbose" activée par défaut. En la désactivant, les variables disparaissent du log.

**Comment by goldendatahub** [comment]
Merci Alex, je clos l'issue.
