### ISSUE TITLE
DB location

### ISSUE THREAD

**Issue by ghys** [yukulehe/gazpar2mqtt#49]
L'emplacement de la DB semble être hardcodé pour une utilisation dans Docker :
https://github.com/yukulehe/gazpar2mqtt/blob/bc7f87688db8f268d969bf196066996bb7dbe268/app/database.py#L10

Pourrait-on avoir un paramètre pour le changer ?
Merci !

**Comment by goldendatahub** [comment]
Salut, bonne remarque. Je m'en occupe.

**Comment by goldendatahub** [comment]
A tester en 0.6.4
