### ISSUE TITLE
Attribution pour un portage?

### ISSUE THREAD

**Issue by defunes43** [yukulehe/gazpar2mqtt#53]
Je suis en train, dans le cadre de la création d'une librairie avec plein de trucs d'accès à l'énergie (avec notamment Linky en plus), et, en particulier, de faire un portage de la partie gazpar.py de ce projet en C#.

Comme ce projet est licencié en GPL, je mettrai le mien sous cette licence aussi, mais je me pose la question de l'attribution de votre travail sur la partie Gazpar. Dans un tel cas, la réponse canonique semble être: [demandez aux intéressés comment ils veulent que leur travail leur soit attribué.](https://softwareengineering.stackexchange.com/questions/167935/proper-attribution-of-derived-work-in-a-gpl-project)

Et du coup, comment souhaitez-vous que votre travail vous soit attribué?

**Comment by goldendatahub** [comment]
Hello,
J'apprécie ta démarche. Aucun souci pour moi, les exemples présentés dans ton lien me conviennent parfaitement.

**Comment by defunes43** [comment]
Merci pour le retour :)

J'ai publié, n'hésites pas si tu veux que je change un truc 

https://github.com/defunes43/EnergyDataAccess/blob/main/LICENSE

**Comment by goldendatahub** [comment]
C'est très bien merci
