### ISSUE TITLE
InfluxDB

### ISSUE THREAD

**Issue by edouardkleinhans** [yukulehe/gazpar2mqtt#60]
Hello, 

Did you plan to add influxDB support for long term storage ?

Regards, 

Edouard

**Comment by goldendatahub** [comment]
Bonjour Edouard,

Oui je travaille actuellement sur un export des datas vers Influxdb v2, plus fourniture d'un dashboard modèle sous grafana.
J'aurais besoin de béta testeurs...

Geoffroy

**Comment by pbranly** [comment]
Bonjour,
J'utilise actuellement une version perso réalisée sur base ssenart et Jeoffrey. 
Celle ci écrit directement dans InfluxDB 
Je ne suis pas sous HAOS mais en HA docker. 
Si tu écris directement aussi dans InfluxDB, cela ne changera rien et je suis preneur de tester ton grafana.
Cdlt
Philippe

**Comment by goldendatahub** [comment]
Salut Philippe,

Je sais que ça vient en plus de ton projet, du coup ça ne te pose pas de souci si je fais de même ?  
Initialement je ne comptais pas faire d'export vers influx, mais je me suis rendu compte que c'était indispensable pour faire une bonne analyse d'historique.
Merci en tout cas pour ton aide sur les tests. C'est pas pour tout de suite, j'ai encore un peu de boulot, mais ça avance bien.

**Comment by pbranly** [comment]
Aucun soucis . A la base, le programme a été fait par Jeoffrey. J'ai ensuite fait plein de mises à jour pour suivre le moteur de base de ssenart et mettre toutes les variables en environnement afin d'en faire un docker compose très simple .
Il est toujours prévu que mon fork reparte chez Jeoffroy . 
Donc n'hésite pas au plus on est au mieux c'est .
Philippe

**Comment by edouardkleinhans** [comment]
Top, merci pour ce retour. Si besoin de testeur, je suis disponible.Pour info, je suis sous Hassos

**Comment by goldendatahub** [comment]
@edouardkleinhans 
Tu es en influxdb v2 sous hassos ?

**Comment by edouardkleinhans** [comment]
Non influx 1

**Comment by goldendatahub** [comment]
C'est ce que je craignais... Pour l'instant je ne prévois pas de portage en v1.
Il faudrait vraiment qu'un add-on HA sous influxdb en v2 soit proposé.

**Comment by edouardkleinhans** [comment]
@yukulehe Je viens d'installer un addon influxdb v2. (https://github.com/Jays-Home-Assistant-Add-ons/repository)

Ca marche plutôt pas mal. (on peut même faire une rétrocompatibilité avec influxdb v1)

Donc, si tu as besoin d'aide pour tester des trucs sur influxdb v2, je suis dispo

**Comment by goldendatahub** [comment]
Hello @edouardkleinhans , la fonctionnalité est dispo dans la nouvelle release (0.8), avec un exemple de dashboard sous grafana.
