### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by titio63** [yukulehe/gazpar2mqtt#68]
Bonjour,
désole pour mon ignorance mais je débute dans HA
Je souhaite recuperer les informations de GARPAR2 MQTT pour les inserer dans la partie energie
j'ai donc installer l'addon, configurer mon mot de passe ainsi que l'identifiant et lancer la connexion.
tout a l'air de fonctionner, le log me dit qul a recuperer des informations mais je ne sais pas comment creer des entités par rapport a ces informations
pourriez vous m'aider

cordialement

**Comment by goldendatahub** [comment]
Hello, tu peux activer le discovery mode (variable HA_DISCOVERY à True) pour que HA génère automatiquement les entités.

**Comment by titio63** [comment]
comme tout bon ignorant, je fais comment?

**Comment by goldendatahub** [comment]
La doc est ton amie ;) 
De la même façon que tu as configuré ton user et ton mot de passe, tu actives le paramètre HASS_DISCOVERY avec la valeur True (soit dans les variables d'environnement soit dans les arguments si tu executes le script manuellement).

**Comment by titio63** [comment]
Bon je crois que je suis très nul
J'ai mis sur HA le mode avance 
Mais je ne trouve pas.
Pour moi le mode discovery était de base enclenché

**Comment by titio63** [comment]
Je viens de regarder 
Mes réglages de gazpar sont bien réglé
Le Mqtt discovery est bien true
Sur mon appli sur ordinateur mqtt explorer voit bien les données de gazpar mais sur ha je ne reçois rien de visible. J'ai redémarré mais toujours rien. 
Je ne comprend pas.

**Comment by goldendatahub** [comment]
Si tu vas dans configuration > appareils, tu devrais tomber sur ton gazpar avec la liste des entités.
Exemple chez moi : 
![image](https://user-images.githubusercontent.com/31646663/157841084-ba987616-1c8e-49c4-9128-7d7257413239.png)

Peut-etre que le discovery est désactivé chez toi dans HA. 

Je te renvoie vers la doc de HA sur le discovery : https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by titio63** [comment]
Bon je n'ai rien, 
je tenvoie ma configuration car je suis parti sur un HA neuf
mon mqtt ne vois rien et cest bien active le discovery
![Capture d’écran 2022-03-11 à 12 28 08](https://user-images.githubusercontent.com/74839136/157859606-12aa48cc-9bee-490d-b855-deba0f354694.png)
![Capture d’écran 2022-03-11 à 12 28 27](https://user-images.githubusercontent.com/74839136/157859610-a9c62816-bdc9-4740-85ff-673e611a3e31.png)
![Capture d’écran 2022-03-11 à 12 28 59](https://user-images.githubusercontent.com/74839136/157859612-f5dff53d-f19b-468d-9b69-a72b9245fbae.png)
![Capture d’écran 2022-03-11 à 12 29 40](https://user-images.githubusercontent.com/74839136/157859614-adb02470-62bc-4f04-b078-e3c525105c27.png)
![Capture d’écran 2022-03-11 à 12 29 56](https://user-images.githubusercontent.com/74839136/157859617-3b32dea0-ca9f-412a-a234-0d6ba2c6bb90.png)
![Capture d’écran 2022-03-11 à 12 30 49](https://user-images.githubusercontent.com/74839136/157859622-5af05d69-0f81-4d5c-911c-1c702473d64d.png)

**Comment by goldendatahub** [comment]
Tu n'as pas activé le discovery dans gazpar2mqtt (comme l'indiques les logs) ...
![image](https://user-images.githubusercontent.com/31646663/157870120-eca64018-847a-4806-adc6-a8d996d11b16.png)

Comme dit précédemment, il faut que tu rajoutes la variable HASS_DISCOVERY: True
![image](https://user-images.githubusercontent.com/31646663/157870196-243cf1c1-30fb-4bd5-a996-f6bd92612435.png)

**Comment by titio63** [comment]
bonjour,
j'ai rajouter la ligne dans config de gazpar, mais rien n'a change.
je lavais pas mis car dans la configuration du module gazpar le mqtt autodiscover etait coche

**Comment by titio63** [comment]
![Capture d’écran 2022-03-11 à 18 16 21](https://user-images.githubusercontent.com/74839136/157915398-70fc7c41-ae1c-4244-82a0-9c7de1f0dcad.png)

**Comment by goldendatahub** [comment]
Le paramètre HASS_DISCOVERY est obligatoire si tu souhaites que le script gazpar2mqtt publie des valeurs dans mqtt au format attendu par HA. 
Je ne connais pas le paramètre que tu évoques mqtt_autodiscover, qui est probablement une option de l'add-on. Pour ton info, je ne gère pas l'add-on et je ne sais pas comment il fonctionne. Je sais juste qu'il encapsule mon appli.
Maintenant que HASS_DISCOVERY est actif, le script gazpar2mqtt a normalement publié des valeurs dans le topic homeassistant/xxx (les logs te fournissent le nom des topics exacts). Un device nommé gazpar a dû être créé avec les entités associées.
Est-ce que tu vois des valeurs publiées dans mqtt sur ces topics ?

**Comment by goldendatahub** [comment]
Parfois un arrêt/relance du serveur HA peut débloquer la situation.

**Comment by titio63** [comment]
j'ai bien essaye. si je te donne un acces avec teamviewer tu peux regarder

**Comment by titio63** [comment]
ce qui m'ennuie c'est que rien apparait dans MQTT 
<img width="464" alt="Capture d’écran 2022-03-11 à 19 00 16" src="https://user-images.githubusercontent.com/74839136/157924033-b1754611-7c1f-438b-997a-2b703b767664.png">

**Comment by goldendatahub** [comment]
Dans ce cas, le problème vient peut être entre tes serveurs HA et MQTT. Tu utilises un add-on MQTT pour HA ou un serveur MQTT à part ?
