### ISSUE TITLE
Use energy values as first line.

### ISSUE THREAD

**Issue by bateast** [yukulehe/gazpar2mqtt#75]
Hello,
thank you for this great tool.

I'm wondering why :

1. you truncate volume values to int (m³ is quite large unit).
    If you get the more precise values, why not keep them.
    → remove `int()` for gas volume storage
3. volume is provided mainly in volume. 
     Though this is the primary measure index, all usages (pricing computation, comparison to other energy source,…) would be done with the kWh energy values (through the timely dependent conversion factor). With the unique conversion factor, past date comparison is not meaningful — my current gas volume consumption can be compared to the consumption one year ago only if I get the conversion factor at both dates.
     → at least provide _energy_ equivalent to all _gas_ mqtt topics

**Comment by bateast** [comment]
Sorry, I see that the int conversion is not from the tool but on data from grdf.

Still, precise gaz volume consumption could be computed from energy / conversion factor. For low gaz volume, the m³ unit is large (10 000 watts·h as a unit) to compare with other energy sources.

I update the title to remove int() conversion assumption.

**Comment by goldendatahub** [comment]
Hello,
J'écris en français car je suppose que tu dois être en France :)
Merci pour ton message. Je m'en occuperai dès que j'aurai un peu de dispo car je suis actuellement en congés paternité.
A++

**Comment by goldendatahub** [comment]
Hello @bateast ,

Actuellement, les mesures périodiques de consommation d'énergie (année en cours, année -1, mois en cours, etc.) se basent sur un delta d'index correspondant à la période, multiplié par le facteur de conversion max de la période. 
Ca me paraît être la moins mauvaise solution.
Si l'on se basait sur les relevés d'energie (en kwh) et qu'on les sommait, alors le résultat serait incorrect du fait de l'absence de nombreux relevés. Il y a en effet de nombreux trous dans les relevés fournis par GRDF.
