### ISSUE TITLE
Captcha solution

### ISSUE THREAD

**Issue by vingerha** [yukulehe/gazpar2mqtt#80]
Hi, as many others, I stopped using this due to the captcha issue but I have now tested a solution meters2ha through an Alpine container. Ubuntu/Debian I could not get to work due to issues with chromium for this approach.
Are you still interested in re-vamping and then maintaining this solution if I can provide a captcha to it?

Added info:
MetersToHa works fine but for me GRDF it is not very reliable in providing the day-by-day data. I am now waiting 3 days and no updates since the last value for the 27th. Since meters2ha currently only exports a json, not too easy to create something to provide a overview.
My thoughts are either to expand meters2ha with a db and from that db I can maybe also add a solution to import the data into long term statistics (alike MyElectricalData does, based on a solution by @chocomega ). Alternative...add db to meters2ha as it is still being supported.

**Comment by goldendatahub** [comment]
Salut. Navré, j'ai effectivement arrêté de maintenir l'application après l'activation (attendue) du Captcha. Je ne suis pas trop favorable à l'intégration d'un résolveur de Captcha (payant, résultat incertain). De plus et surtout, je n'ai plus la disponibilité requise pour travailler sur des projets open source.

**Comment by vingerha** [comment]
Pas une surprise que t'abandonne .... et je suis aligné avec tes idées.
Mais... je suis aussi intéressé d'avoir ma consommation :) 
Avec l'autre solution, GRDF n'est fiable, au moin j'attend des données de hier mais de temps en temps il faut attendre 6 jours...donc j'ai besoin d'une solution base/données
Je vais voir avec meters2ha si je pourrait faire qq plus simple.

**Comment by vingerha** [comment]
FYI, avec grdf de nouveau sans captcha j'ai pu me connecter en ajoutant selenium (et beaucoup de trial&error testing). J'attend qqc dans 2 semaines et je vais continuer avec mon fork
